name: artifact-upload
on: workflow_dispatch

jobs:
  artifact-job:
    runs-on: ubuntu-latest
    steps:
      - name: generate file
        run: echo "test file" >> artifact-file.txt
      - uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: artifact-test-file.txt
