name: CICD2

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        run: echo "cloning the code"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build using docker
        run: echo "building using docker"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "testing the App"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "deploying the code"
