name: conditional
on: 
  push:
    branches: main

jobs:
  conditional-job1:
    runs-on: ubuntu-latest
    steps:
      - name: check if main
        if: github.ref == 'refs/heads/main'
        run: echo "this runs only if it is main branch"

      - name: failed step
        id: demo
        run: exit 1

      - name: run if previous step failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
        run: echo "this runs if previous step fails" 

  conditional-job2:
    runs-on: ubuntu-latest
    steps:
      - name: on-push event
        if: contains(fromJSON('["push"]'), github.event_name)
        run: echo "this runs only if it is push event"
