name: hello workflow
on:
  workflow_dispatch:
jobs:
  greet-job:
    name: greet-job-name
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
    - name: print-date
      run: date      
    - name: echo-hello
      run: echo "Hello from GitHub Actions!"
    - name: print branch name
      run: |
        echo "Branch name is: ${{ github.ref_name }}"
    - name: list files in repo
      run: |
        echo "Files in Repo are:"
        ls -laR
