name: Auto linter

on:
  push:
    paths: "*.py"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: install ruff
        run: pip install ruff
      - name: lint check
        run: ruff check .
