name: manual run
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: environment
        options: 
        - staging
        - production

jobs:
  manual-run-job:
    runs-on: ubuntu-latest
    steps:
    - name: print environment
      run: echo "${{ github.event.name.options }}"
