name: matrix-check
on:
  workflow_dispatch:

jobs:
  python-matrix:
    strategy:
      matrix:
        exclude:
          - os: ubuntu-latest
            version: '3.11'
          - os: ubuntu-22.04-arm
            version: '3.12'
        version:
          - 3.10
          - 3.11
          - 3.12
        os:
          - 'ubuntu-latest'
          - 'ubuntu-22.04-arm'
    runs-on: ${{  matrix.os  }}
    steps:
    - name: apt update
      run: sudo apt-get update -y
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '${{  matrix.version  }}'
    - run: python --version
