name: multi job
on:
  workflow_dispatch:

jobs:
  build:
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build..."
  test:
    name: test job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test..."  
  deploy:
    name: deploy job
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy..."  
