name: pr-check

on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - 'main'

jobs:
  pr-check-job:
    runs-on: ubuntu-latest
    steps:
    - name: Notify job run
      run: |
        echo "PR job running for: ${{ github.ref_name }}"
