name: secrets-check

on: workflow_dispatch

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
    - name: secret step
      env:
        SUPER_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
      if: env.SUPER_SECRET != ''
      run: |
        echo "The secret is set: true"
        echo "$SUPER_SECRET"

    - name: Use secrets as environment variables
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "Docker username is $DOCKER_USERNAME"
        echo "Docker token length: ${#DOCKER_TOKEN}"
